### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by amehmedic** [Plasmonix/Netflixer#26]
Is the checker still working? I tried it with a few workings accounts and they show up as BAD results.

**Comment by YashvirGaming** [comment]
@amehmedic  ofcourse it wont lol because Netflix has Recaptcha V3 now on their site and this python source don't have 
Owner is dead maybe he wont work on it 

Ohh i can make it API tho non skip hits api checker + with better captures or full captures
Also I converted the checker to EXE incluuding with iCON 
using Pyinstaller

Now i could OBFUSCATE the whole thing before Converting to .EXE
![image](https://github.com/Plasmonix/Netflixer/assets/64865096/24141d79-7457-44c7-8dbb-3f33835aaf2d)
